---
title: "HS_MRT"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

setwd("~/Documents/MRT_competition/Case Study")
library(geepack)
library(readr)

# HS_MRT = read.csv("HS_MRT_example.csv")
# 
# current_id = 1
# for (row in 2:(nrow(HS_MRT))) {
#   if( HS_MRT$day[row] < HS_MRT$day[row-1] ) {
#     current_id = current_id + 1
#   }
#   HS_MRT$id[row] = current_id
# }
# 
# summary(as.factor(HS_MRT$id))
# 
# save(HS_MRT, file = "HS_MRT.RData")


load("HS_MRT.RData")
```


### Model 1

```{r warning=FALSE}

# Model 1: WCLS with just a constant effect over time and control variables (logpresteps, constant, day in study)
HS_MRT$MRT_action_c = HS_MRT$MRT_action - mean(HS_MRT$MRT_action)

model_1 = geeglm(MRT_reward ~ MRT_action_c*logpresteps + day ,
                 data = HS_MRT,
                 weights = MRT_avails, 
                 id =id , 
                 scale.fix = T) 

summary(model_1)
```

Centering the logpresteps by its mean

```{r warning=FALSE}
# For model 1 we can try our method with logpresteps as the moderator to reduce noise

HS_MRT$logpresteps_c = HS_MRT$logpresteps - mean(HS_MRT$logpresteps)

model_1 = geeglm(MRT_reward ~ MRT_action_c*logpresteps_c + day ,
                 data = HS_MRT,
                 weights = MRT_avails, 
                 id =id , 
                 scale.fix = T) 

summary(model_1)
```

### Model 2 (removing "day")

```{r warning=FALSE}
# Model 2: WCLS with day in study txt effect and same control variables
model_2 = geeglm(MRT_reward ~ MRT_action_c  + logpresteps,
                 data = HS_MRT,
                 weights = MRT_avails, 
                 id =id , 
                 scale.fix = T) 

summary(model_2)
```


```{r warning=FALSE}
# For model 2: same thing
model_2 = geeglm(MRT_reward ~ MRT_action_c*logpresteps_c,
                 data = HS_MRT,
                 weights = MRT_avails, 
                 id =id , 
                 scale.fix = T) 

summary(model_2)

```

### Model 2 (with day in study)

```{r warning=FALSE}
centering_model = lm(logpresteps ~ day,data = HS_MRT)
HS_MRT$logpresteps_c = HS_MRT$logpresteps - centering_model$fitted.values

# Model 2: WCLS with day in study txt effect and same control variables
model_2 = geeglm(MRT_reward ~ MRT_action_c*day +  logpresteps,
                 data = HS_MRT,
                 weights = MRT_avails, 
                 id =id , 
                 scale.fix = T) 

summary(model_2)
```


```{r warning=FALSE}
# For model 2: same thing
model_2 = geeglm(MRT_reward ~ MRT_action_c* (day +  logpresteps_c),
                 data = HS_MRT,
                 weights = MRT_avails, 
                 id =id , 
                 scale.fix = T) 

summary(model_2)

```

### Model 3

```{r warning=FALSE}

# Model 3: WCLS with day in study and moderators of logpresteps and engagement

model_3 = geeglm(MRT_reward ~ MRT_action_c*(day + logpresteps + engagement),
                 data = HS_MRT,
                 weights = MRT_avails, 
                 id =id , 
                 scale.fix = T) 

summary(model_3)
```

Centering the logpresteps by (1, day)


```{r warning=FALSE}
centering_model = lm(engagement ~ day,data = HS_MRT)
HS_MRT$engagement_c = HS_MRT$engagement - centering_model$fitted.values


model_3 = geeglm(MRT_reward ~ MRT_action_c*(day + logpresteps_c + engagement_c),
                 data = HS_MRT,
                 weights = MRT_avails, 
                 id =id , 
                 scale.fix = T) 

summary(model_3)
```

### Model 4

```{r warning=FALSE}

# For model 3: add dosage as a 3rd moderator in our method.
fit_wcls = geeglm(MRT_reward ~ MRT_action_c*day,
                 data = HS_MRT,
                 weights = MRT_avails, 
                 id =id , 
                 scale.fix = T) 

summary(model_4)
```

```{r warning=FALSE}

centering_model = lm(dosage ~ day,data = HS_MRT)
HS_MRT$dosage_c = HS_MRT$dosage - centering_model$fitted.values
#summary(centering_model)

fit_cwcls = geeglm(MRT_reward ~ MRT_action_c*(day + logpresteps_c + engagement_c + dosage_c),
                 data = HS_MRT,
                 weights = MRT_avails, 
                 id =id , 
                 scale.fix = T) 

summary(model_4)
```

```{r eval=FALSE, include=FALSE}
library(ggplot2)

plot_moderator = function(fit_wcls, fit_cwcls, moderator= "day"){
  var_wcls = matrix(0, nrow = 2, ncol = 2)
  coeff_wcls = coef(fit_wcls)[c("MRT_action_c",paste0("MRT_action_c:", moderator))]
  
  vcov_m = vcov(fit_wcls)
  
  var_wcls[1,1] = vcov_m["MRT_action_c","MRT_action_c"]
  var_wcls[1,2] = vcov_m["MRT_action_c",paste0("MRT_action_c:", moderator)]
  var_wcls[2,1] = var_wcls[1,2]
  var_wcls[2,2] = vcov_m[paste0("MRT_action_c:", moderator),paste0("MRT_action_c:", moderator)]
  
  var_cwcls = matrix(0, nrow = 2, ncol = 2)
  coeff_cwcls = coef(fit_cwcls)[c("MRT_action_c",paste0("MRT_action_c:", moderator))]
  
  vcov_m = vcov(fit_cwcls)
  
  var_cwcls[1,1] = vcov_m["MRT_action_c","MRT_action_c"]
  var_cwcls[1,2] = vcov_m["MRT_action_c",paste0("MRT_action_c:", moderator)]
  var_cwcls[2,1] = var_cwcls[1,2]
  var_cwcls[2,2] = vcov_m[paste0("MRT_action_c:", moderator),paste0("MRT_action_c:", moderator)]
  
  
  
  data = as.data.frame(matrix(NA, nrow = 200, ncol = 5))
  colnames(data) = c("x","y","lower","upper","Method")
  data$x = rep(1:100,2)
  data$Method = rep(c("Centering-WCLS","WCLS"),each = 100)
  
  data$y[1:100] = coeff_cwcls[1]+ coeff_cwcls[2] *data$x[1:100] 
  data$y[101:200] = coeff_wcls[1]+ coeff_wcls[2]*data$x[101:200]
  
  
  
  ########## part 1
  var_cor_cwcls = var_cwcls
  
  calculate_se = function(x) sqrt(t(c(1,x))%*%var_cor_cwcls%*%c(1,x))
  
  se_cor = sapply(data$x[1:100],FUN=calculate_se)
  
  t_quantile <- qt(0.975, 40-length(fit_cwcls[["coefficients"]]))
  
  data$lower[1:100] = data$y[1:100] - t_quantile*se_cor
  data$upper[1:100] = data$y[1:100] + t_quantile*se_cor
  
  
  ####### part2
  
  var_cor_wcls = var_wcls
  
  calculate_se = function(x) sqrt(t(c(1,x))%*%var_cor_wcls%*%c(1,x))
  
  se_cor = sapply(data$x[101:200],FUN=calculate_se)
  
  
  t_quantile <- qt(0.975, 40-length(fit_wcls[["coefficients"]]))
  
  data$lower[101:200] = data$y[101:200] - t_quantile*se_cor
  data$upper[101:200] = data$y[101:200] + t_quantile*se_cor
  
  
  
  p<-ggplot(data=data, aes(x=x, y=y, colour=Method)) + 
    geom_line()+
    geom_ribbon(aes(ymin=lower, ymax=upper), linetype=2, alpha=0.1)+
    xlab(moderator)+
    ylab("MRT Reward change")+
    theme_bw()+
    theme(axis.line = element_line(colour = "black"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank()) +
    geom_hline(yintercept =0, linetype=2)+
    theme(axis.text=element_text(size=12),
          axis.title=element_text(size=14))
  p
  
}
```

